#!/bin/bash

# Check that the input and output directories were provided.
if [ $# -ne 2 ]; then
    echo "Usage: $0 <folder with .json files> <output-separated-folder>" >&2
    exit 1
fi

in="$1"
out="$2"
cti="$out/cti"
is="$out/is"

# Verify that the input directory exists.
if [ ! -d "$in" ]; then
    echo "Error: Folder $in does not exist or is not a directory." >&2
    exit 1
fi

# Verify that the output directory exists.
if [ ! -d "$out" ]; then
    echo "Error: Output folder $out does not exist." >&2
    exit 1
fi

# Verify that the CTI output directory exists.
if [ ! -d "$cti" ]; then
    echo "Error: Folder $cti does not exist. Please create it beforehand." >&2
    exit 1
fi

# Verify that the IS output directory exists.
if [ ! -d "$is" ]; then
    echo "Error: Folder $is does not exist. Please create it beforehand." >&2
    exit 1
fi

# Count the number of students for every course.
IFS=$'\n'
for i in "$in"/*.json; do
    num=$(cat "$i" | jq -r '.[] | [.roles[0].shortname] | @csv' | grep '"student"$' | wc -l)
    echo "\"$(basename "$i" _users.json)\",\"$num\""
done > "$out/num_users.csv"

# Count the number of students for CTI courses.
IFS=$'\n'
for i in "$in"/*.json; do
    base="$(basename "$i" _users.json)"
    num=$(cat "$i" | jq -r '.[] | [.roles[0].shortname] | @csv' | grep '"student"$' | wc -l)
    found=0

    for series in "CA" "CB" "CC" "CD" "C1" "C2" "C3" "C4" "Tehnologia informaţiei" "CTI" "AAC" "ABD" "eGuv" "G" "GMRV" "IA" "ISI" "MTI" "SAS" "SCPD" "SPF" "SRIC" "SSA" "EGOV"; do
        if [[ "$base" =~ [LM]-A[1-4]-S[1-2]-.*-"$series"$ ]]; then
            found=1
            break
        fi
        if [[ "$base" =~ [LM]-A[1-4]-S[1-2]-.*-"$series"- ]]; then
            if ! [[ "$base" =~ -IS$ ]]; then
                found=1
                break
            fi
        fi
    done

    if [ "$found" -ne 0 ]; then
        echo "\"$base\",\"$num\""
    fi
done > "$cti/num_users.csv"

# Count the number of students for IS courses.
IFS=$'\n'
for i in "$in"/*.json; do
    base="$(basename "$i" _users.json)"
    num=$(cat "$i" | jq -r '.[] | [.roles[0].shortname] | @csv' | grep '"student"$' | wc -l)
    found=0

    for series in "CA" "CB" "CC" "CD" "C1" "C2" "C3" "C4" "Tehnologia informaţiei" "CTI" "AAC" "ABD" "eGuv" "G" "GMRV" "IA" "ISI" "MTI" "SAS" "SCPD" "SPF" "SRIC" "SSA" "EGOV"; do
        if [[ "$base" =~ [LM]-A[1-4]-S[1-2]-.*-"$series"$ ]]; then
            found=1
            break
        fi
        if [[ "$base" =~ [LM]-A[1-4]-S[1-2]-.*-"$series"- ]]; then
            if ! [[ "$base" =~ -IS$ ]]; then
                found=1
                break
            fi
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "\"$base\",\"$num\""
    fi
done > "$is/num_users.csv"
